project:
  type: book
prefer-html: true
number-depth: 2
book:
  title: "my_book_again"
  author: "Kevin Williams"
  date: "9/22/2025"
  cover-image: cover.jpg
  favicon: cover.jpg
  repo-url: https://github.com/kwill1992/my_book_again.git
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part 1"
      chapters: 
       - meat.qmd
       - why_me.qmd
       - hexwall.qmd
    - part: "Projects"
      chapters:
       - projects_creation.qmd
       - projects_creation2.qmd
       - projects_hex.qmd
       - projects_openai.qmd
       - rrl_dot_com.qmd
    - part: "Part 2"
      chapters:
       - concepts.qmd
       - summary.qmd
    - references.qmd
    - errors.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

